### PR TITLE
Moving datastore (1) resource to v1beta1 version

### LINKED ISSUE #132: Moving datastore (1) resource to v1beta1 version
Moving datastore 1 resources to v1beta1 version

- [x] [`google_datastore_index`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/datastore_index)

### PR DESCRIPTION
**Pull request by MyzaTaras**
Moving 1 resource to v1beta1 version

- [x] google_datastore_index

### Description of your changes

Fixes #132 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Uptest:
Resource created successfully but Uptest returned error "Index already exist"

Manual:
google_datastore_index:
Screenshot 2023-01-20 at 11 06 14

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/datastore/index.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/datastore/index.yaml"

**Pull request merged**
