### PR TITLE
Bump Terraform provider plugin version to v4.48.0

### LINKED ISSUE #55: Upgrade underlying GCP terraform provider
### What problem are you facing?

The current Terraform provider is outdated.

### How could Official GCP Provider help solve your problem?
Upgrade to the latest Terraform provider for GCP to enable access to more resources and bug fixes

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Fixes #55

Bumps Terraform provider version to `v4.44.1`.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Resource sets tested here:
https://github.com/upbound/provider-gcp/issues/137

### CODE REVIEW

**Comment by bpandranki24** [comment]
@ulucinar is it possible to bump to `v4.47.0` ? 

This is required for: https://github.com/upbound/provider-gcp/issues/90

**Comment by ulucinar** [comment]
The only Terraform schema change reported is as follows between the versions `4.22.0` and `4.48.0`:
```
google_cloudbuild_trigger:1-2
```

**Review by turkenf — APPROVED** [review]
Thanks @ulucinar @sergenyalcin

**Review by sergenyalcin — APPROVED** [review]
Thanks @turkenf @ulucinar

**Pull request merged**
