### PR TITLE
Adding google_compute_backend_service_signed_url_key, google_compute_network_firewall_policy, google_compute_network_firewall_policy_association, google_compute_region_network_firewall_policy, google_compute_region_network_firewall_policy_association, google_compute_snapshot, google_compute_ssl_policy, google_eventarc_channel, google_eventarc_google_channel_config to v1beta1 version

### LINKED ISSUE #175: Moving compute(7), eventarc(2) resources to v1beta1 version
Moving `compute` 7 resources to v1beta1 version
- [x] [google_compute_backend_service_signed_url_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service_signed_url_key)
- [x] [google_compute_network_firewall_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy)
- [x] [google_compute_network_firewall_policy_association](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy_association)
- [x] [google_compute_region_network_firewall_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_firewall_policy)
- [x] [google_compute_region_network_firewall_policy_association](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_firewall_policy_association)
- [x] [google_compute_snapshot](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_snapshot)
- [x] [google_compute_ssl_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_ssl_policy)

Moving `eventarc` 2 resources to v1beta1 version
- [x] [google_eventarc_channel](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_channel)
- [x] [google_eventarc_google_channel_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_google_channel_config)

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes

Adding `compute` 7 resources to v1beta1 version
- [x] [google_compute_backend_service_signed_url_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service_signed_url_key)
- [x] [google_compute_network_firewall_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy)
- [x] [google_compute_network_firewall_policy_association](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy_association)
- [x] [google_compute_region_network_firewall_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_firewall_policy)
- [x] [google_compute_region_network_firewall_policy_association](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_firewall_policy_association)
- [x] [google_compute_snapshot](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_snapshot)
- [x] [google_compute_ssl_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_ssl_policy)

Adding `eventarc` 2 resources to v1beta1 version
- [x] [google_eventarc_channel](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_channel)
- [x] [google_eventarc_google_channel_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_google_channel_config)

Fixes #175 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual & Uptest:
google_compute_backend_service_signed_url_key - https://github.com/upbound/provider-gcp/actions/runs/4065889389
google_compute_network_firewall_policy - https://github.com/upbound/provider-gcp/actions/runs/4065874762
google_compute_network_firewall_policy_association - https://github.com/upbound/provider-gcp/actions/runs/4065936252
google_compute_region_network_firewall_policy - https://github.com/upbound/provider-gcp/actions/runs/4065880303
google_compute_region_network_firewall_policy_association - https://github.com/upbound/provider-gcp/actions/runs/4065953661
google_compute_snapshot - https://github.com/upbound/provider-gcp/actions/runs/4065895131
google_compute_ssl_policy - https://github.com/upbound/provider-gcp/actions/runs/4065901869
google_eventarc_channel - https://github.com/upbound/provider-gcp/actions/runs/4065907277
google_eventarc_google_channel_config - https://github.com/upbound/provider-gcp/actions/runs/4065911655

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/compute/networkfirewallpolicy.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/compute/regionnetworkfirewallpolicy.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/compute/backendservicesignedurlkey.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/compute/snapshot.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/compute/sslpolicy.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/eventarc/googlechannelconfig.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/compute/networkfirewallpolicyassociation.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/compute/regionnetworkfirewallpolicyassociation.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
