### PR TITLE
Use Terraform Plugin SDK to Reconcile MRs

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

This PR employs the `controller.noForkExternal` & `controller.noForkAsyncExternal` external clients from upjet to reconcile MRs without forking any Terraform CLI or Terraform provider processes.

Some more details on these clients can be found [here](https://github.com/crossplane/upjet/pull/294).

I have:

- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by ulucinar** [comment]
There's a successful platform-ref-gcp uptest run [here](https://github.com/upbound/platform-ref-gcp/actions/runs/6946294069) using the `index.docker.io/ulucinar/provider-gcp-{cloudplatform,compute,container,servicenetworking,sql}:v0.39.0-5848867bfc17168b008f3a6c5bc24541baef0fb0` packages built at this point.

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucket.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucket.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucket.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/redis/instance.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/pubsub/litereservation.yaml,examples/pubsub/litesubscription.yaml,examples/pubsub/litetopic.yaml,examples/pubsub/schema.yaml,examples/pubsub/subscriptioniammember.yaml,examples/pubsub/topiciammember.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/monitoring/"

**Comment by erhancagirici** [comment]
/test-examples="examples/logging/"

**Comment by erhancagirici** [comment]
/test-examples="examples/servicenetworking/connection.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/notebooks/"

**Comment by erhancagirici** [comment]
/test-examples="examples/artifact/"

**Comment by erhancagirici** [comment]
/test-examples="examples/gkehub/"

**Comment by erhancagirici** [comment]
/test-examples="examples/cloudrun/v2job.yaml,examples/cloudrun/v2service.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/artifact/registryrepository.yaml,examples/secretmanager/secret.yaml,examples/secretmanager/secretiammember.yaml,examples/secretmanager/secretversion.yaml,examples/cloudrun/v2job.yaml,examples/cloudrun/v2service.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/monitoring/alertpolicy.yaml,examples/monitoring/customservice.yaml,examples/monitoring/dashboard.yaml,examples/monitoring/group.yaml,examples/monitoring/metricdescriptor.yaml,examples/monitoring/notificationchannel.yaml,examples/monitoring/service.yaml,examples/monitoring/slo.yaml,examples/monitoring/uptimecheckconfig.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/spanner/database.yaml,examples/spanner/instance.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/sql/database.yaml,examples/sql/instance.yaml,examples/sql/sourcerepresentationinstance.yaml,examples/sql/user.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/monitoring/alertpolicy.yaml,examples/monitoring/customservice.yaml,examples/monitoring/dashboard.yaml,examples/monitoring/group.yaml,examples/monitoring/metricdescriptor.yaml,,examples/monitoring/service.yaml,examples/monitoring/slo.yaml,examples/monitoring/uptimecheckconfig.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/sql/database.yaml,examples/sql/instance.yaml,examples/sql/sourcerepresentationinstance.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/container/cluster.yaml,examples/container/nodepool.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/sql/user.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/monitoring/alertpolicy.yaml,examples/monitoring/dashboard.yaml,examples/monitoring/group.yaml,examples/monitoring/metricdescriptor.yaml,,examples/monitoring/service.yaml,examples/monitoring/slo.yaml,examples/monitoring/uptimecheckconfig.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/container/nodepool.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/workflows/workflow.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/compute/address.yaml,examples/compute/attacheddisk.yaml,examples/compute/backendservice.yaml,examples/compute/disk.yaml,examples/compute/diskiammember.yaml,examples/compute/diskresourcepolicyattachment.yaml,examples/compute/externalvpngateway.yaml,examples/compute/firewall.yaml,examples/compute/globaladdress.yaml,examples/compute/globalnetworkendpoint.yaml,examples/compute/globalnetworkendpointgroup.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/compute/vpngateway.yaml,examples/compute/targettcpproxy.yaml,examples/compute/targetsslproxy.yaml,examples/compute/targetpool.yaml,examples/compute/targetinstance.yaml,examples/compute/subnetworkiammember.yaml,examples/compute/subnetwork.yaml,examples/compute/sslpolicy.yaml,examples/compute/sslcertificate.yaml,examples/compute/securitypolicy.yaml,examples/compute/routerpeer.yaml,examples/compute/routernat.yaml,examples/compute/router.yaml,examples/compute/route.yaml,examples/compute/resourcepolicy.yaml,examples/compute/regionurlmap.yaml,examples/compute/regiontargethttpsproxy.yaml,examples/compute/regiontargethttpproxy.yaml,examples/compute/regionsslcertificate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/healthcheck.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/httphealthcheck.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/image.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/imageiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/instancefromtemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/instancegroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/interconnectattachment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/network.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/networkfirewallpolicyassociation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/nodetemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/packetmirroring.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/projectdefaultnetworktier.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regionbackendservice.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regiondisk.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regiondiskresourcepolicyattachment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regionhealthcheck.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regioninstancegroupmanager.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regionnetworkfirewallpolicy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regiontargethttpproxy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regiontargethttpproxy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regiontargethttpsproxy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regionurlmap.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/route.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/router.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/routernat.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/routerpeer.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/securitypolicy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/sslcertificate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/sslpolicy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/subnetwork.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/subnetworkiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/targetinstance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/targetpool.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/targetsslproxy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/targettcpproxy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/vpngateway.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/projectiamauditconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/serviceaccountkey.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/projectservice.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/projectusageexportbucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/serviceaccountiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/projectiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/artifact/repositoryiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshubdataexchange.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshubdataexchangeiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshublisting.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/datasetaccess.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/datatransferconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservationassignment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/routine.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/table.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucket.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucketaccesscontrol.yaml,examples/storage/bucketacl.yaml,examples/storage/bucketiammember.yaml,examples/storage/bucketobject.yaml,examples/storage/defaultobjectaccesscontrol.yaml,examples/storage/defaultobjectacl.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/cloudfunctions2/function.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/compute/backendbucket.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/compute/targethttpsproxy.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/compute/urlmap.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucketaccesscontrol.yaml,examples/storage/bucketiammember.yamlexamples/storage/defaultobjectaccesscontrol.yaml,examples/storage/defaultobjectacl.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucketacl.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucketiammember.yaml,examples/storage/defaultobjectaccesscontrol.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/artifact/repositoryiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshubdataexchange.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshubdataexchangeiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshublisting.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/datasetaccess.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/datatransferconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/datatransferconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservationassignment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/routine.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/routine.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/networkpeering.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/networkpeeringroutesconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/v2job.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/regionperinstanceconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/forwardingrule.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/backendservicesignedurlkey.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/reservation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/globalforwardingrule.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/snapshot.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sql/user.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshubdataexchangeiammember.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/analyticshublisting.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/v2service.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/container/nodepool.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudplatform/projectusageexportbucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/storage/bucketacl.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/monitoring/customservice.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/reservation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/v2job.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/compute/instancefromtemplate.yaml"

**Comment by erhancagirici** [comment]
\test-examples="examples/compute/snapshot.yaml"

**Comment by erhancagirici** [comment]
\test-examples="examples/redis/instance.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/monitoring/notificationchannel.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/compute/snapshot.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/bucketobject.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/bigquery/datatransferconfig.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/redis/instance.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/bigquery/table.yaml,examples/cloudrun/service.yaml,examples/compute/disk.yaml,examples/compute/firewall.yaml,examples/compute/healthcheck.yaml,examples/compute/instance.yaml,examples/compute/regionbackendservice.yaml,examples/compute/regiondisk.yaml,examples/compute/regionhealthcheck.yaml,examples/compute/router.yaml,examples/compute/routernat.yaml,examples/compute/securitypolicy.yaml,examples/compute/sslpolicy.yaml,examples/compute/subnetwork.yaml,examples/container/cluster.yaml,examples/dataflow/job.yaml,examples/logging/projectsink.yaml,examples/spanner/database.yaml,examples/sql/instance.yaml,examples/storage/bucket.yaml,examples/storage/bucketacl.yaml,examples/compute/instancefromtemplate.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/storage/objectacl.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/certificatemanager/certificate.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/bigquery/table.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/firewall.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/healthcheck.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/regionbackendservice.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/instance.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/regiondisk.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/regionhealthcheck.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/securitypolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/sslpolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/spanner/database.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/sql/instance.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/routernat.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/instancefromtemplate.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/instancetemplate.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thank you! LGTM!

**Review by erhancagirici — APPROVED** [review]

**Review by turkenf — APPROVED** [review]
Thank you @ulucinar, LGTM.

**Pull request merged**
