### PR TITLE
Test bigquery & dataflow group with uptest

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

This PR attempts to test the bigquery & dataflow groups with the uptest tooling.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

The results are recorded in PR https://github.com/upbound/provider-gcp/pull/56.

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/datatransferconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservationassignment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/routine.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/datatransferconfig.yaml"

**Comment by ulucinar** [comment]
We had to enable the following APIs for the GCP project to get the tests working:
- bigquerydatatransfer.googleapis.com
- dataflow.googleapis.com
- bigqueryreservation.googleapis.com
- iam.googleapis.com (was already enabled for the project)
- ...

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservationassignment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/reservationassignment.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/bigquery/datasetaccess.yaml"

**Comment by ulucinar** [comment]
Hi @turkenf,
After fixing the permissions issue, the datasourceaccess has succeeded. The old status checks have disappeared with the new commit but there is no need to rerun the tests as currently the only changed example manifest is the reservationassignment manifest.

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/connection.yaml"

**Review by turkenh — APPROVED** [review]
Looking good 👍

**Comment by ulucinar** [comment]
Thank you @turkenf!

**Pull request merged**
