### PR TITLE
Support auth annotations for Upbound

### PR DESCRIPTION
**Pull request by jastang**
### Description of your changes
Bumps the build submodule to pick up changes that support adding ProviderConfig documentation for Upbound via the auth annotations (`auth.yaml`).

Fixes https://github.com/upbound/squad-upbound-cloud/issues/1218

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Built and pushed the config & monolithic packages using this PR. The packages will be shared via a different communication channel.

### CODE REVIEW

**Comment by jastang** [comment]
Note -- this is not functioning in its current state. The package-level annotation is being injected, but not the CRD-level annotations on the ProviderConfig (even with a raw `up xpkg build ...` command). Needs further investigation before being ready for review.

**Comment by ulucinar** [comment]
Hi @jastang,
If you prefer, I can take over from here and do the investigation. How do you feel about it?

**Comment by jastang** [comment]
> Hi @jastang,
> 
> If you prefer, I can take over from here and do the investigation. How do you feel about it?

Go for it @ulucinar ! I am out til next week, so no rush on my end.

**Comment by ulucinar** [comment]
Hi @jastang,
The issue with the PR was that we currently don't support amending the provider package metadata with auth annotation for the `v1` version of `Provider.meta`. Currently, only `v1alpha1` is supported:
https://github.com/upbound/up/blob/7776c9db2c93d1f8dcce6ece05944dcf4a84ef2a/internal/xpkg/build.go#L196

I've rebased the PR and it's ready for review.

**Comment by ulucinar** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by jastang** [comment]
> Hi @jastang, The issue with the PR was that we currently don't support amending the provider package metadata with auth annotation for the `v1` version of `Provider.meta`. Currently, only `v1alpha1` is supported: https://github.com/upbound/up/blob/7776c9db2c93d1f8dcce6ece05944dcf4a84ef2a/internal/xpkg/build.go#L196
> 
> I've rebased the PR and it's ready for review.

thanks @ulucinar! I don't think that should block this PR, but is there a reason to only support `v1alpha1`? cc @nullable-eth

**Review by sergenyalcin — APPROVED** [review]
Thanks @jastang LGTM!

**Pull request merged**
