### PR TITLE
Adding google_dataproc_autoscaling_policy, google_dataproc_cluster, google_dataproc_job, google_dataproc_workflow_template to v1beta1 version

### LINKED ISSUE #131: Moving dataproc (4) resources to v1beta1 version
Moving dataproc 4 resources to v1beta1 version

- [x] [`google_dataproc_autoscaling_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_autoscaling_policy)
- [x] [`google_dataproc_cluster`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster)
- [x] [`google_dataproc_job`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_job)
- [x] [`google_dataproc_workflow_template`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template)

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes
Adding dataproc 4 resources to v1beta1 version

- [x] [`google_dataproc_autoscaling_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_autoscaling_policy)
- [x] [`google_dataproc_cluster`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster)
- [x] [`google_dataproc_job`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_job)
- [x] [`google_dataproc_workflow_template`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template)

Fixes #131 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual & Uptest:
google_dataproc_autoscaling_policy - https://github.com/upbound/provider-gcp/actions/runs/3967355097
google_dataproc_cluster - https://github.com/upbound/provider-gcp/actions/runs/3967361753
google_dataproc_job - https://github.com/upbound/provider-gcp/actions/runs/3967454653
google_dataproc_workflow_template - https://github.com/upbound/provider-gcp/actions/runs/3967369862

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/dataproc/autoscalingpolicy.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/dataproc/cluster.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/dataproc/workflowtemplate.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/dataproc/job.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
