### PR TITLE
Moving datacatalog (2) resources to v1beta1 version

### LINKED ISSUE #103: Moving datacatalog (2) resources to v1beta1 version
Moving 2 resources to v1beta1 version

- [x] [google_data_catalog_tag](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_tag)
- [x] [google_data_catalog_tag_template](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_tag_template)

### PR DESCRIPTION
**Pull request by MyzaTaras**
Moving 2 resources to v1beta1 version

- [x] [google_data_catalog_tag](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_tag)
- [x] [google_data_catalog_tag_template](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_tag_template)

### Description of your changes

Fixes #103 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manual & Uptest:
google_data_catalog_tag - [link](https://github.com/upbound/provider-gcp/actions/runs/3938340896/jobs/6736922257)
google_data_catalog_tag_template - [link](https://github.com/upbound/provider-gcp/actions/runs/3938097643/jobs/6736394927)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/datacatalog/tagtemplate.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datacatalog/tag.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datacatalog/tag.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datacatalog/tag.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datacatalog/tag.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datacatalog/tagtemplate.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/datacatalog/tag.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @MyzaTaras LGTM!

**Pull request merged**
