### PR TITLE
Moving activedirectory (1) resource to v1beta1 version

### LINKED ISSUE #121: Moving activedirectory (1) resource to v1beta1 version
Moving activedirectory 1 resource to v1beta1 version

- [x] [`google_active_directory_domain`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/active_directory_domain)

### PR DESCRIPTION
**Pull request by MyzaTaras**
Moving 1 resource to v1beta1 version

- [x] google_active_directory_domain

### Description of your changes

Fixes #121 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manual & Uptest:
google_active_directory_domain - [link](https://github.com/upbound/provider-gcp/actions/runs/3948615878/jobs/6758825268)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/activedirectory/domain.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/activedirectory/domain.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/activedirectory/domain.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @MyzaTaras LGTM!

**Pull request merged**
