### PR TITLE
Adding google_vertex_ai_dataset, google_vertex_ai_featurestor, google_vertex_ai_featurestore_entitytype, google_vertex_ai_tensorboard, google_filestore_backup, google_filestore_snapshot to v1beta1 version

### LINKED ISSUE #183: Moving vertexai (4), filestore (2) resources to v1beta1 version
Moving `vertexai` 4 resources to v1beta1 version
- [x] [google_vertex_ai_dataset](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_dataset)
- [x] [google_vertex_ai_featurestore](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore)
- [x] [google_vertex_ai_featurestore_entitytype](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore_entitytype)
- [x] [google_vertex_ai_tensorboard](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_tensorboard)

Moving `filestore` 2 resources to v1beta1 version
- [x] [google_filestore_backup](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_backup)
- [x] [google_filestore_snapshot](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_snapshot)

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes

Adding `vertexai` 4 resources to v1beta1 version
- [x] [google_vertex_ai_dataset](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_dataset)
- [x] [google_vertex_ai_featurestore](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore)
- [x] [google_vertex_ai_featurestore_entitytype](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore_entitytype)
- [x] [google_vertex_ai_tensorboard](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_tensorboard)

Adding `filestore` 2 resources to v1beta1 version
- [x] [google_filestore_backup](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_backup)
- [x] [google_filestore_snapshot](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_snapshot)

Fixes #183 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual & Uptest:

google_vertex_ai_dataset - https://github.com/upbound/provider-gcp/actions/runs/4025045310
google_vertex_ai_featurestore - https://github.com/upbound/provider-gcp/actions/runs/4025048451
google_vertex_ai_featurestore_entitytype - https://github.com/upbound/provider-gcp/actions/runs/4043534736
google_vertex_ai_tensorboard - https://github.com/upbound/provider-gcp/actions/runs/4025052545
google_filestore_backup - https://github.com/upbound/provider-gcp/actions/runs/4025042618
google_filestore_snapshot - https://github.com/upbound/provider-gcp/actions/runs/4025059535

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/filestore/backup.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/vertexai/dataset.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/vertexai/featurestore.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/vertexai/tensorboard.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/vertexai/featurestoreentitytype.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/filestore/snapshot.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/vertexai/featurestoreentitytype.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
