### PR TITLE
Feature/add project shared vpc resources selectors

### LINKED ISSUE #80: Moving compute (2) resources to v1beta1 version
Moving 2 resources in the `compute` group:
- [ ] [`google_compute_shared_vpc_host_project`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_shared_vpc_host_project)
- [ ] [`google_compute_shared_vpc_service_project`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_shared_vpc_service_project)

Note: These two resources have commented-out configurations in the respective [config/external_name.go](https://github.com/upbound/provider-gcp/blob/090f08482cf66c04771bbcf4d983c4138e97d234/config/external_name.go#L229).

Please also see:
https://github.com/upbound/provider-gcp/pull/69#issuecomment-1346156271

### PR DESCRIPTION
**Pull request by bradkwadsworth-mw**
### Description of your changes
~Enabled `google_compute_shared_vpc_host_project` and `google_compute_shared_vpc_service_project`. It would appear that `google_compute_shared_vpc_service_project` requires the `google-beta` provider in order to work in some situations such as when the Shared VPC Admin role is set at the folder level. Has there been an discussion on creating another Upjet provider based on the `google-beta` Terraform provider?~
Added host project and service project selectors for SharedVPCHostProject and SharedVPCServiceProject resources.

Fixes #80 

I have:

- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Tested the creation of a GCP project and enabled that project as a VPC host project. Also created a service project and attached it to the host project.
Screenshot 2023-03-31 at 11 14 57 AM

### CODE REVIEW

**Comment by turkenf** [comment]
Require status checks changed could you please rebase this PR?

**Comment by sergenyalcin** [comment]
/test-examples="examples/compute/sharedvpchostproject.yaml"

**Comment by bradkwadsworth-mw** [comment]
/test-examples="examples/compute/sharedvpchostproject.yaml"

**Comment by turkenf** [comment]
Closing & reopening to trigger the Github workflow runs.

**Comment by turkenf** [comment]
/test-examples="examples/compute/sharedvpchostproject.yaml"

**Review by turkenh — APPROVED** [review]
Resources in this PR require manual intervention, i.e. privileged access in multiple gcp projects, so ignoring failing uptest runs. I am not sure why it failed despite the`manual-internvention` annotation, though.

**Pull request merged**
