### PR TITLE
Bump native tf provider to version 5.19.0

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

**In this PR:**

- Upgraded Terraform provider version to `v5.17.0`
- The `provider-gcp-cloudiot` family provider containing the two resources listed below was deleted
   1.  `Device.cloudiot.gcp.upbound.io/v1beta1`
   2. `Registry.cloudiot.gcp.upbound.io/v1beta1`
- Deleted reference for `cloud_storage_config.bucket` from `Subscription.pubsub.gcp.upbound.io/v1beta1` resource
- Added separate uptestable example for `DomainMapping.cloudrun.gcp.upbound.io/v1beta1`
- Removed deleted field `size` and add `initialSize` for `NodeGroup.compute.gcp.upbound.io/v1beta1`
- Removed manual intervention and add pre-delete-hook for `SSLCert.sql.gcp.upbound.io/v1beta1`
- Added manual intervention and fixed example manifest for `Function.cloudfunctions2.gcp.upbound.io/v1beta1`
- Fixed update loop and added description for `Job.dataflow.gcp.upbound.io/v1beta1`
- Set `deletionProtection: false` for `Cluster.container.gcp.upbound.io/v1beta1`
- Fixed external name configuration for `Membership.gkehub.gcp.upbound.io/v1beta1` and `DNSAuthorization.certificatemanager.gcp.upbound.io/v1beta1`

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tested manually and with uptest, and added to [comments](https://github.com/upbound/provider-gcp/pull/465#issuecomment-1980443457) below.

### CODE REVIEW

**Comment by turkenf** [comment]
**Breaking CRD schema changes**

1. `package/crds/alloydb.gcp.upbound.io_instances.yaml` Failed will test manually
2. `package/crds/bigquery.gcp.upbound.io_routines.yaml` => 
3. `package/crds/cloudfunctions2.gcp.upbound.io_functions.yaml` => Failed will test manually
4. `package/crds/cloudrun.gcp.upbound.io_domainmappings.yaml` => Manual
5. `package/crds/cloudrun.gcp.upbound.io_v2jobs.yaml` => 
6. `package/crds/cloudrun.gcp.upbound.io_v2services.yaml` => 
7. `package/crds/compute.gcp.upbound.io_nodegroups.yaml` => Failed will test manually
8. `package/crds/compute.gcp.upbound.io_routernats.yaml` => 
9. `package/crds/container.gcp.upbound.io_clusters.yaml` => 
10. `package/crds/eventarc.gcp.upbound.io_triggers.yaml` => Failed will test manually
11. `package/crds/privateca.gcp.upbound.io_certificates.yaml` => Manual
12. `package/crds/secretmanager.gcp.upbound.io_secrets.yaml` => 
13. `package/crds/sql.gcp.upbound.io_databaseinstances.yaml` => 
14. `package/crds/sql.gcp.upbound.io_sslcerts.yaml` => Manual

**Native schema version changes**

1. `google_beyondcorp_app_gateway` => 
2. `google_bigquery_job` => Manual
3. `google_cloud_run_domain_mapping` => Manual
4. `google_cloud_run_service` => Manual
5. `google_container_cluster` => 
6. `google_dataflow_job` => Manual
7. `google_dataproc_cluster` => Failed will test manually
8. `google_dataproc_workflow_template` => 
9. `google_datastream_private_connection` => Failed will test manually
10. `google_gke_hub_membership` => Failed will test manually
11. `google_ml_engine_model` => 
12. `google_notebooks_instance` => 
13. `google_storage_bucket` =>

**Comment by turkenf** [comment]
/test-examples="examples/alloydb/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/routine.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudfunctions2/function.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/v2job.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/v2service.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/nodegroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/routernat.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/container/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eventarc/trigger.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/secretmanager/secret.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sql/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dataproc/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dataproc/workflowtemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/datastream/privateconnection.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/gkehub/membership.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/mlengine/model.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/notebooks/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/storage/bucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/routernat.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/globaladdress.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/nodegroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eventarc/trigger.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sql/sslcert.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/gkehub/membership.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudplatform/serviceaccount.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bigquery/routine.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/domainmapping.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/v2job.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudrun/v2service.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/nodegroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/routernat.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/container/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/secretmanager/secret.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sql/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sql/sslcert.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/beyondcorp/appgateway.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dataproc/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dataproc/workflowtemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/mlengine/model.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/notebooks/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/storage/bucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/compute/routernat.yaml"

**Comment by turkenf** [comment]
### After v5.19.0 

**Breaking CRD schema changes**

1. `package/crds/alloydb.gcp.upbound.io_instances.yaml` Uptest failed, manually tested successfully
```

```
2. `package/crds/bigquery.gcp.upbound.io_routines.yaml` => 
3. `package/crds/cloudfunctions2.gcp.upbound.io_functions.yaml` => Manual
```

```
4. `package/crds/cloudrun.gcp.upbound.io_domainmappings.yaml` => https://github.com/upbound/provider-gcp/actions/runs/8163100522
5. `package/crds/cloudrun.gcp.upbound.io_v2jobs.yaml` => https://github.com/upbound/provider-gcp/actions/runs/8163101475
6. `package/crds/cloudrun.gcp.upbound.io_v2services.yaml` => https://github.com/upbound/provider-gcp/actions/runs/8163102443
7. `package/crds/compute.gcp.upbound.io_nodegroups.yaml` => https://github.com/upbound/provider-gcp/actions/runs/8163103245
8. `package/crds/compute.gcp.upbound.io_routernats.yaml` => 
9. `package/crds/container.gcp.upbound.io_clusters.yaml` => 
10. `package/crds/eventarc.gcp.upbound.io_triggers.yaml` => Uptest failed, manually tested successfully
```

```
11. `package/crds/privateca.gcp.upbound.io_certificates.yaml` => Manual
```
s
```
12. `package/crds/secretmanager.gcp.upbound.io_secrets.yaml` => https://github.com/upbound/provider-gcp/actions/runs/8163106231
13. `package/crds/sql.gcp.upbound.io_databaseinstances.yaml` => https://github.com/upbound/provider-gcp/actions/runs/8163107062
14. `package/crds/sql.gcp.upbound.io_sslcerts.yaml` => https://github.com/upbound/provider-gcp/actions/runs/8163107821

**Native schema version changes**

1. `google_beyondcorp_app_gateway` => https://github.com/upbound/provider-gcp/actions/runs/8163135232
2. `google_bigquery_job` => Manual
3. `google_certificate_manager_dns_authorization`
4. `google_cloud_run_domain_mapping` => https://github.com/upbound/provider-gcp/actions/runs/8163100522
5. `google_cloud_run_service` => The example of the DomainMapping resource also includes the Service resource: https://github.com/upbound/provider-gcp/actions/runs/8163100522
6. `google_container_cluster` => 
7. `google_dataflow_job` =>  Manual
```

```
8. `google_dataproc_cluster` => https://github.com/upbound/provider-gcp/actions/runs/8163136389
9. `google_dataproc_workflow_template` => https://github.com/upbound/provider-gcp/actions/runs/8163137196
10. `google_datastream_private_connection` => Uptest failed, manually tested successfully
```

```
11. `google_gke_hub_membership` => Uptest failed, manually tested successfully
```

```
12. `google_ml_engine_model` => https://github.com/upbound/provider-gcp/actions/runs/8163138008
13. `google_notebooks_instance` => https://github.com/upbound/provider-gcp/actions/runs/8163139144
14. `google_storage_bucket` => https://github.com/upbound/provider-gcp/actions/runs/8163139880

**Comment by turkenf** [comment]
/test-examples="examples/certificatemanager/dnsauthorization.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/container/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/gkehub/membership.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/certificatemanager/dnsauthorization.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/certificatemanager/dnsauthorization.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @turkenf LGTM!

**Pull request merged**
