### PR TITLE
Moving cloudplatform(1) resource to v1beta1 version

### LINKED ISSUE #213: Moving cloudplatform(1) resource to v1beta1 version
Moving `cloudplatform` 1 resource to v1beta1 version

- [x] [`google_project_iam_custom_role`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam_custom_role)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
Moving 1 resource to v1beta1 version
- [x] [`google_project_iam_custom_role`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam_custom_role) 

Fixes #213 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual:
`google_project_iam_custom_role ` - due to account for Uptest running doesn't have permission for role creation.
Screenshot 2023-02-08 at 11 22 22

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/cloudplatform/projectiamcustomrole.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/cloudplatform/projectiamcustomrole.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/cloudplatform/projectiamcustomrole.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/cloudplatform/projectiamcustomrole.yaml"

**Review by turkenf — APPROVED** [review]
Thanks @MyzaTaras

**Pull request merged**
